### ISSUE TITLE
요구사항 정의

### ISSUE THREAD

**Issue by sjy7392** [kimyeonsooo/opensourceBasic#1]
주제 : 나이 예측 프로그램

1. opencv 사용해 얼굴 인식
2. 나이 인식 모델 학습시키기
3. 나이 인식 알고리즘 구현하기

현재까지 정해진 사항들인데 추가하거나 수정하고 싶은 부분 있으면 남겨주세요.

**Comment by kimyeonsooo** [comment]
인식 데이터는 학습된 모델을 가져 오고, 나이 인식과 더불어 성별 인식 기능을 추가시키면 좋지 않을까요?

**Comment by sjy7392** [comment]
얼굴 인식 학습 시킨 데이터가 있어서 그거 가져오고 거기에 기능 덧붙이는 걸로 하는게 좋을 것 같아요.
현재 이미지는 확실히 진행시킬 거고 동영상, 카메라를 통한 인식까지 해보는 걸로 할게요

**Comment by sjy7392** [comment]
새로이 건의하실 부분 있으면 새로운 이슈 남겨주세요~
