### ISSUE TITLE
남은 일정

### ISSUE THREAD

**Issue by kimyeonsooo** [kimyeonsooo/opensourceBasic#16]
마감까지 6일 남았는데 남은 주요 태스크 있는 분 계신가요

**Comment by sjy7392** [comment]
8일까지는 다 merge 하는 걸로 해요!

**Comment by sjy7392** [comment]
merge 다 올려서 이슈 닫겠습니다.
지금 발표준비랑 사진 업로드 빼곤 없는 것 같아서.
주요 태스크 있으시면 이슈 남겨주세요.
