### ISSUE TITLE
re: feature detection 풀리퀘 불가

### ISSUE THREAD

**Issue by kimyeonsooo** [kimyeonsooo/opensourceBasic#31]
해당 이슈 해결 안 돼서 새로운 브랜치 만들어 같은 파일 등록하는 것으로 하겠습니다

**Comment by sjy7392** [comment]
네 알겠습니다. 11:59에 마감이라 제가 혹시 몰라서 브랜치 만들어뒀어요.
작업 다 하시면 답글 주세요
