### ISSUE TITLE
tkinter 디자인

### ISSUE THREAD

**Issue by sjy7392** [kimyeonsooo/opensourceBasic#5]
tkinter 디자인을 지금 구상 중인데 사실 복잡한 건 없고 일단 버튼부터 디자인 하려 하는데 이미지 사용하는게 좋을까요? 아님 간단하게 포토샵 사용해도 좋아요

**Comment by kimyeonsooo** [comment]
포토샵으로 하는 것도 좋은데 tkinter 라이브러리에서 이미지 적용을 허용하나요? 조금 더 찾아본 후에 시도해 볼게요

**Comment by sjy7392** [comment]
네 이미지 허용해요
적합한 이미지 한 번 찾아볼게요
