### ISSUE TITLE
협업에 관해

### ISSUE THREAD

**Issue by kimyeonsooo** [kimyeonsooo/opensourceBasic#6]
지금 각각의 파트를 각자 작업하는 중이라 모두 merge 했을 때 프로그램이 잘 돌아갈지 확신이 안 서요 일정 잡구 확인하도록 해 봐요

**Comment by sjy7392** [comment]
내일 수업 시간 끝나고 만나서 확인해봐요! 전 지금 snapshot기능은 얼추 되었고 video 작업 중이에요
